### ISSUE TITLE
npm run start 失败

### ISSUE THREAD

**Issue by beyondspider** [wjkang/quasar-admin-server#2]
npm run start

> fty.koa2@1.0.0 start quasar-admin-server
> gulp nodemon

internal/util/inspect.js:31
const types = internalBinding('types');
              ^

ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15

 at internal/util/inspect.js:31:15
    at req_ (/Users/i323566/work/git/github.com/wjkang/quasar-admin-server/node_modules/natives/index.js:137:5)
    at require (quasar-admin-server/node_modules/natives/index.js:110:12)
    at util.js:25:21
    at req_ (quasar-admin-server/node_modules/natives/index.js:137:5)
    at require (quasar-admin-server/node_modules/natives/index.js:110:12)
    at fs.js:42:21
    at req_ (quasar-admin-server/node_modules/natives/index.js:137:5)
    at Object.req [as require] (quasar-admin-server/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (quasar-admin-server/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fty.koa2@1.0.0 start: `gulp nodemon`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fty.koa2@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by JSjump** [comment]
找到解决办法了吗兄弟

**Comment by beyondspider** [comment]
么有啊！你也遇到类似的错误吗？

**Comment by athenatd** [comment]
npm install natives@1.1.6
[https://github.com/gulpjs/gulp/issues/2280](url) , It's work for me..

**Comment by liyujiang-gzu** [comment]
> npm install natives@1.1.6
> [https://github.com/gulpjs/gulp/issues/2280](url) , It's work for me..

的确如此，感谢
